GET http://127.0.0.1:8000/api/v1/test/ HTTP/1.1

###

GET http://127.0.0.1:8000/api/v1/test/123 HTTP/1.1

###

POST http://127.0.0.1:8000/api/v1/test/ HTTP/1.1

{
    "name": "test"
}

###

POST http://127.0.0.1:8000/api/v1/test/aoai HTTP/1.1

{
    "user_prompt": "what does gpt mean?"
}